// Code generated by protoc-gen-go. DO NOT EDIT.
// source: im_protobuf.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 查询用户是否在线
type QueryUsersOnlineReq struct {
	AppId                uint32   `protobuf:"varint,1,opt,name=appId,proto3" json:"appId,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryUsersOnlineReq) Reset()         { *m = QueryUsersOnlineReq{} }
func (m *QueryUsersOnlineReq) String() string { return proto.CompactTextString(m) }
func (*QueryUsersOnlineReq) ProtoMessage()    {}
func (*QueryUsersOnlineReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_62691ff0994625a6, []int{0}
}

func (m *QueryUsersOnlineReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUsersOnlineReq.Unmarshal(m, b)
}
func (m *QueryUsersOnlineReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUsersOnlineReq.Marshal(b, m, deterministic)
}
func (m *QueryUsersOnlineReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUsersOnlineReq.Merge(m, src)
}
func (m *QueryUsersOnlineReq) XXX_Size() int {
	return xxx_messageInfo_QueryUsersOnlineReq.Size(m)
}
func (m *QueryUsersOnlineReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUsersOnlineReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUsersOnlineReq proto.InternalMessageInfo

func (m *QueryUsersOnlineReq) GetAppId() uint32 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *QueryUsersOnlineReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type QueryUsersOnlineRsp struct {
	RetCode              uint32   `protobuf:"varint,1,opt,name=retCode,proto3" json:"retCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	Online               bool     `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryUsersOnlineRsp) Reset()         { *m = QueryUsersOnlineRsp{} }
func (m *QueryUsersOnlineRsp) String() string { return proto.CompactTextString(m) }
func (*QueryUsersOnlineRsp) ProtoMessage()    {}
func (*QueryUsersOnlineRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_62691ff0994625a6, []int{1}
}

func (m *QueryUsersOnlineRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUsersOnlineRsp.Unmarshal(m, b)
}
func (m *QueryUsersOnlineRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUsersOnlineRsp.Marshal(b, m, deterministic)
}
func (m *QueryUsersOnlineRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUsersOnlineRsp.Merge(m, src)
}
func (m *QueryUsersOnlineRsp) XXX_Size() int {
	return xxx_messageInfo_QueryUsersOnlineRsp.Size(m)
}
func (m *QueryUsersOnlineRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUsersOnlineRsp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUsersOnlineRsp proto.InternalMessageInfo

func (m *QueryUsersOnlineRsp) GetRetCode() uint32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *QueryUsersOnlineRsp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *QueryUsersOnlineRsp) GetOnline() bool {
	if m != nil {
		return m.Online
	}
	return false
}

// 发送消息
type SendMsgReq struct {
	Seq                  string   `protobuf:"bytes,1,opt,name=seq,proto3" json:"seq,omitempty"`
	AppId                uint32   `protobuf:"varint,2,opt,name=appId,proto3" json:"appId,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Msg                  string   `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
	IsLocal              bool     `protobuf:"varint,6,opt,name=isLocal,proto3" json:"isLocal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMsgReq) Reset()         { *m = SendMsgReq{} }
func (m *SendMsgReq) String() string { return proto.CompactTextString(m) }
func (*SendMsgReq) ProtoMessage()    {}
func (*SendMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_62691ff0994625a6, []int{2}
}

func (m *SendMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMsgReq.Unmarshal(m, b)
}
func (m *SendMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMsgReq.Marshal(b, m, deterministic)
}
func (m *SendMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMsgReq.Merge(m, src)
}
func (m *SendMsgReq) XXX_Size() int {
	return xxx_messageInfo_SendMsgReq.Size(m)
}
func (m *SendMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendMsgReq proto.InternalMessageInfo

func (m *SendMsgReq) GetSeq() string {
	if m != nil {
		return m.Seq
	}
	return ""
}

func (m *SendMsgReq) GetAppId() uint32 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *SendMsgReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SendMsgReq) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SendMsgReq) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SendMsgReq) GetIsLocal() bool {
	if m != nil {
		return m.IsLocal
	}
	return false
}

type SendMsgRsp struct {
	RetCode              uint32   `protobuf:"varint,1,opt,name=retCode,proto3" json:"retCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	SendMsgId            string   `protobuf:"bytes,3,opt,name=sendMsgId,proto3" json:"sendMsgId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMsgRsp) Reset()         { *m = SendMsgRsp{} }
func (m *SendMsgRsp) String() string { return proto.CompactTextString(m) }
func (*SendMsgRsp) ProtoMessage()    {}
func (*SendMsgRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_62691ff0994625a6, []int{3}
}

func (m *SendMsgRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMsgRsp.Unmarshal(m, b)
}
func (m *SendMsgRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMsgRsp.Marshal(b, m, deterministic)
}
func (m *SendMsgRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMsgRsp.Merge(m, src)
}
func (m *SendMsgRsp) XXX_Size() int {
	return xxx_messageInfo_SendMsgRsp.Size(m)
}
func (m *SendMsgRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMsgRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SendMsgRsp proto.InternalMessageInfo

func (m *SendMsgRsp) GetRetCode() uint32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *SendMsgRsp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *SendMsgRsp) GetSendMsgId() string {
	if m != nil {
		return m.SendMsgId
	}
	return ""
}

// 获取用户列表
type GetUserListReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserListReq) Reset()         { *m = GetUserListReq{} }
func (m *GetUserListReq) String() string { return proto.CompactTextString(m) }
func (*GetUserListReq) ProtoMessage()    {}
func (*GetUserListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_62691ff0994625a6, []int{4}
}

func (m *GetUserListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserListReq.Unmarshal(m, b)
}
func (m *GetUserListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserListReq.Marshal(b, m, deterministic)
}
func (m *GetUserListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserListReq.Merge(m, src)
}
func (m *GetUserListReq) XXX_Size() int {
	return xxx_messageInfo_GetUserListReq.Size(m)
}
func (m *GetUserListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserListReq proto.InternalMessageInfo

type GetUserListRsp struct {
	RetCode              uint32   `protobuf:"varint,1,opt,name=retCode,proto3" json:"retCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	UserId               []string `protobuf:"bytes,3,rep,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserListRsp) Reset()         { *m = GetUserListRsp{} }
func (m *GetUserListRsp) String() string { return proto.CompactTextString(m) }
func (*GetUserListRsp) ProtoMessage()    {}
func (*GetUserListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_62691ff0994625a6, []int{5}
}

func (m *GetUserListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserListRsp.Unmarshal(m, b)
}
func (m *GetUserListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserListRsp.Marshal(b, m, deterministic)
}
func (m *GetUserListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserListRsp.Merge(m, src)
}
func (m *GetUserListRsp) XXX_Size() int {
	return xxx_messageInfo_GetUserListRsp.Size(m)
}
func (m *GetUserListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserListRsp proto.InternalMessageInfo

func (m *GetUserListRsp) GetRetCode() uint32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *GetUserListRsp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *GetUserListRsp) GetUserId() []string {
	if m != nil {
		return m.UserId
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryUsersOnlineReq)(nil), "protobuf.QueryUsersOnlineReq")
	proto.RegisterType((*QueryUsersOnlineRsp)(nil), "protobuf.QueryUsersOnlineRsp")
	proto.RegisterType((*SendMsgReq)(nil), "protobuf.SendMsgReq")
	proto.RegisterType((*SendMsgRsp)(nil), "protobuf.SendMsgRsp")
	proto.RegisterType((*GetUserListReq)(nil), "protobuf.GetUserListReq")
	proto.RegisterType((*GetUserListRsp)(nil), "protobuf.GetUserListRsp")
}

func init() { proto.RegisterFile("im_protobuf.proto", fileDescriptor_62691ff0994625a6) }

var fileDescriptor_62691ff0994625a6 = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xcd, 0x4e, 0xf2, 0x40,
	0x14, 0xfd, 0x4a, 0xf9, 0xeb, 0xfd, 0x82, 0xc1, 0x91, 0x98, 0x91, 0x68, 0x42, 0xba, 0x62, 0x61,
	0xba, 0xd0, 0x85, 0x6b, 0x61, 0x61, 0x48, 0x20, 0x62, 0x89, 0x1b, 0x63, 0x42, 0xa0, 0xbd, 0x36,
	0x4d, 0x28, 0x1d, 0x66, 0x8a, 0x91, 0x77, 0xf0, 0x15, 0x7d, 0x17, 0x33, 0xd3, 0x9f, 0x01, 0x53,
	0x5d, 0xb0, 0x9a, 0x7b, 0xce, 0xbd, 0xf7, 0xe4, 0xcc, 0x99, 0x81, 0xd3, 0x30, 0x9a, 0x33, 0x1e,
	0x27, 0xf1, 0x72, 0xfb, 0xe6, 0xa8, 0x82, 0x34, 0x73, 0x6c, 0x0f, 0xe1, 0xec, 0x69, 0x8b, 0x7c,
	0xf7, 0x2c, 0x90, 0x8b, 0xc7, 0xf5, 0x2a, 0x5c, 0xa3, 0x8b, 0x1b, 0xd2, 0x81, 0xda, 0x82, 0xb1,
	0x91, 0x4f, 0x8d, 0x9e, 0xd1, 0x6f, 0xb9, 0x29, 0x20, 0xe7, 0x50, 0xdf, 0x0a, 0xe4, 0x23, 0x9f,
	0x56, 0x7a, 0x46, 0xdf, 0x72, 0x33, 0x64, 0xcf, 0x4b, 0x44, 0x04, 0x23, 0x14, 0x1a, 0x1c, 0x93,
	0x61, 0xec, 0x63, 0x26, 0x93, 0x43, 0x29, 0x84, 0x9c, 0x4f, 0x44, 0x90, 0x0b, 0xa5, 0x48, 0xf2,
	0xb1, 0x5a, 0xa7, 0x66, 0xcf, 0xe8, 0x37, 0xdd, 0x0c, 0xd9, 0x9f, 0x06, 0xc0, 0x0c, 0xd7, 0xfe,
	0x44, 0x04, 0xd2, 0x5d, 0x1b, 0x4c, 0x81, 0x1b, 0x25, 0x6a, 0xb9, 0xb2, 0xd4, 0x7e, 0x2b, 0xe5,
	0x7e, 0xcd, 0x7d, 0xbf, 0x84, 0x40, 0x35, 0xd9, 0x31, 0xa4, 0x55, 0xc5, 0xaa, 0x5a, 0x6a, 0x46,
	0x22, 0xa0, 0xb5, 0x54, 0x33, 0x12, 0x81, 0xb4, 0x1f, 0x8a, 0x71, 0xec, 0x2d, 0x56, 0xb4, 0xae,
	0xdc, 0xe4, 0xd0, 0x7e, 0xd5, 0x6e, 0x8e, 0xba, 0xe6, 0x25, 0x58, 0x22, 0xdd, 0x2f, 0xac, 0x69,
	0xc2, 0x6e, 0xc3, 0xc9, 0x03, 0x26, 0x32, 0xcb, 0x71, 0x28, 0x12, 0x17, 0x37, 0xf6, 0xcb, 0x21,
	0x73, 0x6c, 0xb4, 0x45, 0x16, 0xa6, 0xce, 0xe2, 0xe6, 0xcb, 0x00, 0xeb, 0xde, 0xf3, 0x66, 0xc8,
	0xdf, 0x91, 0x13, 0x17, 0xda, 0x3f, 0x5f, 0x92, 0x5c, 0x39, 0xc5, 0xef, 0x29, 0xf9, 0x2a, 0xdd,
	0xbf, 0xda, 0x82, 0xd9, 0xff, 0xc8, 0x1d, 0x34, 0xb2, 0xb4, 0x48, 0x47, 0xcf, 0xea, 0xe7, 0xec,
	0x96, 0xb0, 0x6a, 0x71, 0x08, 0xff, 0xf7, 0xae, 0x4d, 0xa8, 0x1e, 0x3b, 0xcc, 0xa7, 0xfb, 0x4b,
	0x47, 0x8a, 0x0c, 0xae, 0xe1, 0x22, 0x8c, 0x9d, 0x80, 0x33, 0xcf, 0xc1, 0x8f, 0x45, 0xc4, 0x56,
	0x28, 0x8a, 0xe9, 0x41, 0x6b, 0x9a, 0x55, 0xea, 0x9c, 0x1a, 0xcb, 0xba, 0x6a, 0xdd, 0x7e, 0x07,
	0x00, 0x00, 0xff, 0xff, 0x7e, 0x7d, 0x02, 0x74, 0x34, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccServerClient is the client API for AccServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccServerClient interface {
	// 查询用户是否在线
	QueryUsersOnline(ctx context.Context, in *QueryUsersOnlineReq, opts ...grpc.CallOption) (*QueryUsersOnlineRsp, error)
	// 发送消息
	SendMsg(ctx context.Context, in *SendMsgReq, opts ...grpc.CallOption) (*SendMsgRsp, error)
	// 获取用户列表
	GetUserList(ctx context.Context, in *GetUserListReq, opts ...grpc.CallOption) (*GetUserListRsp, error)
}

type accServerClient struct {
	cc *grpc.ClientConn
}

func NewAccServerClient(cc *grpc.ClientConn) AccServerClient {
	return &accServerClient{cc}
}

func (c *accServerClient) QueryUsersOnline(ctx context.Context, in *QueryUsersOnlineReq, opts ...grpc.CallOption) (*QueryUsersOnlineRsp, error) {
	out := new(QueryUsersOnlineRsp)
	err := c.cc.Invoke(ctx, "/protobuf.AccServer/QueryUsersOnline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accServerClient) SendMsg(ctx context.Context, in *SendMsgReq, opts ...grpc.CallOption) (*SendMsgRsp, error) {
	out := new(SendMsgRsp)
	err := c.cc.Invoke(ctx, "/protobuf.AccServer/SendMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accServerClient) GetUserList(ctx context.Context, in *GetUserListReq, opts ...grpc.CallOption) (*GetUserListRsp, error) {
	out := new(GetUserListRsp)
	err := c.cc.Invoke(ctx, "/protobuf.AccServer/GetUserList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccServerServer is the server API for AccServer service.
type AccServerServer interface {
	// 查询用户是否在线
	QueryUsersOnline(context.Context, *QueryUsersOnlineReq) (*QueryUsersOnlineRsp, error)
	// 发送消息
	SendMsg(context.Context, *SendMsgReq) (*SendMsgRsp, error)
	// 获取用户列表
	GetUserList(context.Context, *GetUserListReq) (*GetUserListRsp, error)
}

// UnimplementedAccServerServer can be embedded to have forward compatible implementations.
type UnimplementedAccServerServer struct {
}

func (*UnimplementedAccServerServer) QueryUsersOnline(ctx context.Context, req *QueryUsersOnlineReq) (*QueryUsersOnlineRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryUsersOnline not implemented")
}
func (*UnimplementedAccServerServer) SendMsg(ctx context.Context, req *SendMsgReq) (*SendMsgRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMsg not implemented")
}
func (*UnimplementedAccServerServer) GetUserList(ctx context.Context, req *GetUserListReq) (*GetUserListRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserList not implemented")
}

func RegisterAccServerServer(s *grpc.Server, srv AccServerServer) {
	s.RegisterService(&_AccServer_serviceDesc, srv)
}

func _AccServer_QueryUsersOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUsersOnlineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccServerServer).QueryUsersOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.AccServer/QueryUsersOnline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccServerServer).QueryUsersOnline(ctx, req.(*QueryUsersOnlineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccServer_SendMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccServerServer).SendMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.AccServer/SendMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccServerServer).SendMsg(ctx, req.(*SendMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccServer_GetUserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccServerServer).GetUserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.AccServer/GetUserList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccServerServer).GetUserList(ctx, req.(*GetUserListReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.AccServer",
	HandlerType: (*AccServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryUsersOnline",
			Handler:    _AccServer_QueryUsersOnline_Handler,
		},
		{
			MethodName: "SendMsg",
			Handler:    _AccServer_SendMsg_Handler,
		},
		{
			MethodName: "GetUserList",
			Handler:    _AccServer_GetUserList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "im_protobuf.proto",
}
